spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm97966
    password: 120205
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

server:
  port: 8080

# Ativar console web do H2
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console

# Swagger/OpenAPI personalizado (opcional)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

weather:
  api:
    key: 7a6fd8c2f5180b86bdc1001b59c22c6a